### ISSUE TITLE
Connecting to my own application using the REST API

### ISSUE THREAD

**Issue by rudyvk** [ewjmulder/hue-bridge-simulator#1]
Hi, in the readme you state that I should look into the RESTMenu class for more information on the needed response from my own application. Somehow I don't get it. What is the response required from the various HTTP requests to the backend, do you have a list of that?

I don't intend to use Java as I simply don't understand it (never used it before). Therefore I just need to know what the plain HTML responses need to be to connect to my own application.

It probably doesn't matter, but in my logging I currently get an "Could not extract response: no su                                                                                                                                  itable HttpMessageConverter found for response type" error and I assume that I'm just returning the wrong response...

**Comment by ewjmulder** [comment]
Hi, nice to see you are using my project! It should be no problem to use something else then Java, as the API is based on text based JSON responses. The main idea is to return a JSON representation of an array of MenuItem's: https://github.com/ewjmulder/hue-bridge-simulator/blob/master/rest-api/src/main/java/com/programyourhome/huebridgesimulator/model/menu/MenuItem.java
If you are unfamiliar with JSON, please read a little about that first.

The MIME type of the response should be 'application/json' and the contents will look something like this:

```
[
  {
    "name": "menuItemName",
    "on": false,
    "color": {
      "red": 0,
      "green": 255,
     "blue": 0
    }
  },
    ... (menu item 2 .. n)
]
```

So for every menu item you can tell Toon the name, whether it's on or off and the color of the 'light'. I'm currently at work and cannot run a live test, so I might have a typo in the example above. Let me know if you can get it working.

**Comment by rudyvk** [comment]
Thanks for the explanation. I implemented it in a PHP script that controls EnerGenie power strips. It's still a crude setup, but it works like it should. The PHP json_encode() function works a charm for encoding messages like this. Somehow I looked at your code and just couldn't make up the JSON reply that was needed. If I read it back now, it all makes sense.
Date: Wed, 6 Apr 2016 04:30:03 -0700

**Comment by ewjmulder** [comment]
Cool, glad I could help out, enjoy!

I'm closing this issue. If you need any more help, just let me know.
